In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent=[  'the glass of milk',
         'the glass of juice',
        'the cup of tea',
       'I am a good boy',
        'I am a good developer',
         'understand the meaning of words',
        'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size =10000

In [8]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7360, 4227, 9775, 1993],
 [7360, 4227, 9775, 6111],
 [7360, 579, 9775, 5099],
 [3073, 3428, 3140, 829, 4666],
 [3073, 3428, 3140, 829, 6138],
 [8478, 7360, 4625, 9775, 1994],
 [1214, 6093, 6539, 829]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7360 4227 9775 1993]
 [   0    0    0    0 7360 4227 9775 6111]
 [   0    0    0    0 7360  579 9775 5099]
 [   0    0    0 3073 3428 3140  829 4666]
 [   0    0    0 3073 3428 3140  829 6138]
 [   0    0    0 8478 7360 4625 9775 1994]
 [   0    0    0    0 1214 6093 6539  829]]


In [13]:
dim = 10
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.summary


<bound method Model.summary of <keras.src.engine.sequential.Sequential object at 0x0000013CF1B13F90>>

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 190ms/step


array([[[ 0.03929475, -0.01405381,  0.02959063, -0.04190478,
          0.0097382 ,  0.00954822, -0.04470711,  0.0134706 ,
          0.04097792,  0.00027395],
        [ 0.03929475, -0.01405381,  0.02959063, -0.04190478,
          0.0097382 ,  0.00954822, -0.04470711,  0.0134706 ,
          0.04097792,  0.00027395],
        [ 0.03929475, -0.01405381,  0.02959063, -0.04190478,
          0.0097382 ,  0.00954822, -0.04470711,  0.0134706 ,
          0.04097792,  0.00027395],
        [ 0.03929475, -0.01405381,  0.02959063, -0.04190478,
          0.0097382 ,  0.00954822, -0.04470711,  0.0134706 ,
          0.04097792,  0.00027395],
        [-0.00117463, -0.03721101,  0.03533171, -0.03276222,
          0.01737902,  0.02122829,  0.01687502, -0.0062299 ,
         -0.04933142, -0.04948635],
        [ 0.01597266, -0.04085315, -0.03873418, -0.00107908,
          0.00780473,  0.04473558,  0.03076776, -0.04891599,
          0.03381449, -0.03132081],
        [-0.00169595,  0.02305675, -0.02609074, -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 7360, 4227, 9775, 1993])