In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent=[  'the glass of milk',
         'the glass of juice',
        'the cup of tea',
       'I am a good boy',
        'I am a good developer',
         'understand the meaning of words',
        'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size =10000

In [8]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7360, 4227, 9775, 1993],
 [7360, 4227, 9775, 6111],
 [7360, 579, 9775, 5099],
 [3073, 3428, 3140, 829, 4666],
 [3073, 3428, 3140, 829, 6138],
 [8478, 7360, 4625, 9775, 1994],
 [1214, 6093, 6539, 829]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7360 4227 9775 1993]
 [   0    0    0    0 7360 4227 9775 6111]
 [   0    0    0    0 7360  579 9775 5099]
 [   0    0    0 3073 3428 3140  829 4666]
 [   0    0    0 3073 3428 3140  829 6138]
 [   0    0    0 8478 7360 4625 9775 1994]
 [   0    0    0    0 1214 6093 6539  829]]
